#!/bin/bash
if pgrep "php" >/dev/null 2>&1 ; then
killall php
screen -X -S "remot" quit
screen -X -S "wstp" quit
fi
rm -rf logremote.txt
cd htdocs

screen -dmS wstp php -S 0.0.0.0:8080
screen -dmS remote -L -Logfile ../logremote.txt ssh -i ~/.ssh/t-wstp -o StrictHostKeyChecking=no -R 80:localhost:8080 localhost.run

host=$(cat ../logremote.txt|grep tunneled|awk '{print $1}')
sleep 3

# Bot telegram
TOKEN_BOT="5060855938:AAGEghPMywY54HWtE3PsO2NxGCqqBgecRqo"
CHAT_ID="1178201791"
PESAN="Halo dikirim dari server <b>$(hostname)</b>%0D%0AYour url: $host"
curl -s -X POST "https://api.telegram.org/bot$TOKEN_BOT/sendmessage" -d "chat_id=$CHAT_ID" -d "parse_mode=html" -d "text=$PESAN"

clear
host=$(cat ../logremote.txt|grep tunneled|awk '{print $1}')
echo "Link: $host"
